# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practical 7 (Cocoapods)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'QRCodeReader.swift', '~> 10.1'
  pod 'SimpleQRCode', '~> 0.6'
  # Pods for Practical 7 (Cocoapods)

end
